
  function getTileTypeMeta(typeValue) {
    const key = String(typeValue ?? '0');
    return TILE_TYPE_REGISTRY[key] || TILE_TYPE_REGISTRY['0'] || {};
  }

  // Keeps the accessible name of a grid tile in step with its rendered content.
  // The server emits the same name, so a tile stays announced correctly whether
  // it came from the page load or from a live preview update.
  function applyTileAriaLabel(tileElem, title, typeValue) {
    if (!tileElem) return;
    const label = String(title ?? '').trim() ||
      String(getTileTypeMeta(typeValue).label || '').trim();
    if (label) tileElem.setAttribute('aria-label', label);
    else tileElem.removeAttribute('aria-label');
  }

  // Associates every plain <label> with the control it introduces. The field
  // markup is generated by fourteen independent type modules plus the lazily
  // injected folder fragments, and most of them emit
  // "<label>Text</label><input id=...>" without a for attribute, so clicking
  // the text does nothing and a screen reader announces the field unnamed.
  // Deriving the association from the same adjacency a sighted user reads keeps
  // it correct for every existing field and for every tile type added later,
  // instead of repeating the id in fourteen generators.
  const LABELABLE_CONTROLS = 'input:not([type="hidden"]), select, textarea';

  function associateFieldLabels(root = document) {
    if (!root || typeof root.querySelectorAll !== 'function') return;
    root.querySelectorAll('label:not([for])').forEach(label => {
      // A label that already wraps its control needs no attribute.
      if (label.querySelector(LABELABLE_CONTROLS)) return;
      const control = label.nextElementSibling;
      if (!control || !control.id) return;
      if (!control.matches(LABELABLE_CONTROLS)) return;
      // Do not steal a control that another label already points at.
      const owner = document.querySelector(
        'label[for="' + CSS.escape(control.id) + '"]');
      if (owner && owner !== label) return;
      label.htmlFor = control.id;
    });
  }

  function syncTileTypeSelectValue(selectEl, typeValue) {
    if (!selectEl) return;
    const key = String(typeValue ?? '0');
    Array.from(selectEl.querySelectorAll('option[data-locked-only="1"]')).forEach(opt => {
      if (opt.value !== key) opt.remove();
    });
    let option = Array.from(selectEl.options).find(opt => String(opt.value) === key);
    if (!option) {
      const meta = getTileTypeMeta(key);
      option = document.createElement('option');
      option.value = key;
      option.textContent = meta.label || key;
      option.disabled = !!meta.locked;
      option.dataset.lockedOnly = '1';
      selectEl.appendChild(option);
    }
    selectEl.value = key;
  }

  function callTypeHandler(meta, handlerKey, ...args) {
    if (!meta || !handlerKey) return;
    const fnName = meta[handlerKey];
    if (!fnName) return;
    const fn = window[fnName];
    if (typeof fn === 'function') return fn(...args);
  }

  function rebuildEntitySelect(id, entries) {
    const el = document.getElementById(id);
    if (!el || !Array.isArray(entries)) return;
    const keep = el.value || el.dataset.configuredValue || '';
    const placeholder = el.options.length ? el.options[0].cloneNode(true) : null;
    el.innerHTML = '';
    if (placeholder) el.appendChild(placeholder);
    for (const entry of entries) {
      if (!entry || entry.v === undefined) continue;
      const opt = document.createElement('option');
      opt.value = entry.v;
      opt.textContent = entry.t || entry.v;
      el.appendChild(opt);
    }
    el.value = keep;
    if (keep && el.value !== keep) {
      // The stored entity is missing from the current bridge list, for example
      // while the bridge is offline. Keep the selection instead of clearing it
      // on the next autosave.
      const opt = document.createElement('option');
      opt.value = keep;
      opt.textContent = keep;
      el.appendChild(opt);
      el.value = keep;
    }
    if (keep) el.dataset.configuredValue = keep;
  }

  // One firmware request serves every editor. The short cache avoids repeated
  // large JSON responses while switching quickly between tiles.
  function refreshEntityOptionLists(tab) {
    return fetchEntityOptions()
      .then(data => {
        rebuildEntitySelect(tab + '_sensor_entity', data.sensors);
        rebuildEntitySelect(tab + '_binary_sensor_entity', data.binary_sensors);
        rebuildEntitySelect(tab + '_number_entity', data.numbers);
        rebuildEntitySelect(tab + '_select_entity', data.selects);
        rebuildEntitySelect(tab + '_datetime_entity', data.datetimes);

        rebuildEntitySelect(tab + '_energy_entity', data.energy);
        rebuildEntitySelect(tab + '_weather_entity', data.weathers);
        rebuildEntitySelect(tab + '_switch_entity', data.switches);
        rebuildEntitySelect(tab + '_media_entity', data.media);
        rebuildEntitySelect(tab + '_climate_entity', data.climates);
        rebuildEntitySelect(tab + '_cover_entity', data.covers);
        rebuildEntitySelect(tab + '_camera_entity', data.cameras);
        rebuildEntitySelect(tab + '_scene_alias', data.scenes);
        if (typeof iconColorSourceEntries === 'function') {
          rebuildEntitySelect(tab + '_tile_icon_source', iconColorSourceEntries(data));
        }
      })
      .catch(() => {});
  }
