#!/usr/bin/env python3
"""Regenerates src/network/cloud/cloud_ca_bundle.cpp from ESP-IDF's CA list.

The ZHAC Cloud transport verifies the cloud's TLS certificate against an
ESP-IDF certificate bundle. The core's mbedTLS library embeds the full Mozilla
bundle (about 69 KB), which does not fit the M5Stack Tab5 app slot, so the
firmware defines the bundle symbols itself with ESP-IDF's "common CA" subset
(cmn_crt_authorities.csv, the same list as
CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_CMN).

Usage: python3 tools/generate-cloud-ca-bundle.py <path to esp-idf>
Use the ESP-IDF release that matches the Arduino core (3.3.7 = release/v5.5).
Needs the Python 'cryptography' package, which ESP-IDF's gen_crt_bundle.py uses.
"""

import hashlib
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src/network/cloud/cloud_ca_bundle.cpp"


def idf_version(idf: pathlib.Path) -> str:
    text = (idf / "tools/cmake/version.cmake").read_text(encoding="utf-8")
    parts = [re.search(rf"IDF_VERSION_{name} (\d+)", text).group(1)
             for name in ("MAJOR", "MINOR", "PATCH")]
    return "v" + ".".join(parts)


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    idf = pathlib.Path(sys.argv[1]).resolve()
    bundle_dir = idf / "components/mbedtls/esp_crt_bundle"
    with tempfile.TemporaryDirectory() as work:
        subprocess.run(
            [sys.executable, str(bundle_dir / "gen_crt_bundle.py"),
             "--input", str(bundle_dir / "cacrt_all.pem"),
             "--filter", str(bundle_dir / "cmn_crt_authorities.csv"), "-q"],
            cwd=work, check=True)
        data = (pathlib.Path(work) / "x509_crt_bundle").read_bytes()

    rows = []
    for offset in range(0, len(data), 16):
        chunk = data[offset:offset + 16]
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    source = f"""// ZHAC Cloud transport: root certificates for the cloud's TLS certificate.
//
// Generated by tools/generate-cloud-ca-bundle.py -- do not edit by hand.
// ESP-IDF {idf_version(idf)} gen_crt_bundle.py, Mozilla CA list filtered by
// cmn_crt_authorities.csv (the CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_CMN
// set), {len(data):,} bytes, SHA-256 {hashlib.sha256(data).hexdigest()}.
//
// esp_crt_bundle.c in the core's mbedTLS library refers to these two symbols.
// Defining them here keeps the core's full 69 KB bundle out of the image (the
// Tab5 app slot has no room for it). Nothing else in the firmware uses a
// certificate bundle: the update check and artwork downloads run without one.
#include <stdint.h>

extern "C" const uint8_t kHomeTilesCaBundle[{len(data)}] asm(
    "_binary_x509_crt_bundle_start") __attribute__((used, aligned(4))) = {{
{chr(10).join(rows)}
}};

asm(".global _binary_x509_crt_bundle_end\\n"
    ".set _binary_x509_crt_bundle_end, _binary_x509_crt_bundle_start + {len(data)}\\n");
"""
    OUTPUT.write_text(source, encoding="utf-8", newline="\n")
    print(f"{OUTPUT.relative_to(ROOT)}: {len(data)} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
